### ISSUE TITLE
[HELIX-817] Support for multiple instance group tags for Job config

### ISSUE THREAD

**Issue by narendly** [apache/helix#323] opened 2019-06-24 17:10 UTC
Currently we can set only one instance group tag for a job. 
 
jobCfg.setInstanceGroupTag("INSTANCEGROUPTAG");
 
It will be really helpful to support support multiple instance group tags for one job so that the job can be run either in group A or group B. Through this, we can support more advanced scheduling use cases like in Node Affinity in Kubernetes [1]
 
[1] https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

**Comment by jiajunwang** [comment] 2019-06-24 17:18
What's the difference between using multiple instance group tags and
defining a new tag that includes the desired scope?
The second solution is supported right now and maybe easier to use.

Best Regards,
Jiajun

**Comment by DImuthuUpe** [comment] 2019-06-24 18:31
@jiajunwang Good question. We can add tags to instances as much as we want. But the problem is, is it scalable? I'm not sure whether there is a straightforward way to update the instance config tag dynamically with out restarting participants. I usually set the tag by calling InstanceConfig.addTag(tag). In my use case, I need to dynamically set the target instance / group for a job based on some other external metrics. In that case it would be easy to manipulate the tags at JobConfig level rather than InstanceConfig level.

**Comment by jiajunwang** [comment] 2019-06-24 20:15
@DImuthuUpe, by supporting both sides configuration, we definitely cover more use cases. I think it's very nice to have feature.

To clarify, the instance config update does not require restarting participants.

In addition, I want to better understand your needs. By "dynamically set the target instance / group", can you give us some examples of the external metrics that you might use?

**Comment by desaikomal** [comment] 2023-04-08 19:49
Trying to clean up the bug backlog in open-helix. Is this feature still required?
If not, can we please close this? @jiajunwang - what do you suggest?

**Comment by jiajunwang** [comment] 2023-04-08 21:07
Can we evaluate if we can dynamically update the instance tag as Dimuthu
mentioned in 2019? If this is doable (which I belive so), then I think we
can close it.

Best Regards,
Jiajun

**Closed** 2024-02-23 00:14 UTC

**Comment by AlecHenx** [comment] 2024-07-17 03:00
Did the issue be solved? I encounter the same issue with @DImuthuUpe . In my case, the relation between task and resource(or data, instance) is controlled by our logics. So we only use task framework, NO resource management framework.

The only way can we dispatch tasks to instances under our logic is instance tag. But we cannot set instance tag of a job in runtime.
