### ISSUE TITLE
Unexpected randomness in the WAGED rebalancer partition assignment

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#772] opened 2020-02-17 05:28 UTC
One problem we noticed in the test is that the Baseline and Best possible assignment diverge dramatically when a single resource is scaled up or down. One of the most possible root causes is some unexpected randomness in the algorithm so the baseline and best possible assignment are calculated in a slightly different way.
Based on my current investigation, this is caused by a tie evaluation score. For example, when we scale down a resource from 2 replicas to 1 replica, the algorithm finds 2 potential locations (from the previous assignment) with the same evaluation score. It is possible that the baseline calculation chooses placement A and the best possible calculation chooses placement B.

To address this problem, the following code in the ConstraintBasedAlgorithm.java is most related.

>     return candidateNodes.parallelStream().map(node -> new HashMap.SimpleEntry<>(node,
>         getAssignmentNormalizedScore(node, replica, clusterContext)))
>         .max((nodeEntry1, nodeEntry2) -> {
>           int scoreCompareResult = nodeEntry1.getValue().compareTo(nodeEntry2.getValue());
>           if (scoreCompareResult == 0) {
>             // If the evaluation scores of 2 nodes are the same, the algorithm assigns the replica
>             // to the idle node first.
>             int idleScore1 = busyInstances.contains(nodeEntry1.getKey().getInstanceName()) ? 0 : 1;
>             int idleScore2 = busyInstances.contains(nodeEntry2.getKey().getInstanceName()) ? 0 : 1;
>             return idleScore1 - idleScore2;
>           } else {
>             return scoreCompareResult;
>           }
>         }).map(Map.Entry::getKey);

We need to sort the candidates even their scores and isBusy flags are all equal.

**Comment by jiajunwang** [comment] 2020-02-17 05:30
@nealsun-linkedin Do you think you can help to fix this issue?
To fix this, we need to first confirm the theory. Then after the code change, we need to add a proper test case.

**Comment by NealSun96** [comment] 2020-02-18 18:13
Please assign this issue to me, @jiajunwang , thank you!

**Comment by NealSun96** [comment] 2020-03-12 18:27
Update to the issue: after experiments and discussions, it is concluded that the divergence is not caused by "unexpected randomness" in the algorithm. When the IdealState is changed (which is necessary to scale a resource up or down), the Baseline is recalculated; due to the design of the algorithm, the new Baseline could be very different from the old Baseline depending on the order of resources. Therefore, the divergence is caused by the change of Baseline, while the Best Possible is respecting the old Baseline. 
As a result, to combat divergence, the answer lies within the algorithm design; there is no clean-cut solution that "eliminates divergence". We cannot eliminate the difference between old Baseline and new Baseline because eliminating it is minimizing movement while sacrificing replica evenness - we need to achieve a balance between the two factors. I will continue to do research on this topic. 
In terms of the scope of this issue, the tie-breaking code change will still go through to make scoring deterministic.

**Closed** 2020-03-13 22:28 UTC
Labels: bug
